# Generated by Django 4.0.4 on 2022-05-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('marriage_status', models.CharField(blank=True, choices=[('S', 'single'), ('M', 'married')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Updating', 'Updating'), ('Closed', 'Closed')], default='Updating', max_length=10)),
                ('daily_salary', models.BigIntegerField(default=0)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_income.courier')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('weekly_salary', models.BigIntegerField(default=0)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_income.courier')),
                ('daily_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_income.dailysalary')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncreaseOfIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('increase_income', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('Calculated', 'Calculated'), ('Not calculated', 'Not calculated')], default='Not calculated', max_length=15)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_income.courier')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeOfCourier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('income_of_travel', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('Calculated', 'Calculated'), ('Not calculated', 'Not calculated')], default='Not calculated', max_length=15)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_income.courier')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DecreaseOfIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('decrease_income', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('Calculated', 'Calculated'), ('Not calculated', 'Not calculated')], default='Not calculated', max_length=15)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_income.courier')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
    ]
