# Generated by Django 4.0.4 on 2022-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0003_alter_incomeofcourier_income_of_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decreaseofincome',
            name='decrease_income',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='incomeofcourier',
            name='income_of_travel',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='increaseofincome',
            name='increase_income',
            field=models.PositiveBigIntegerField(),
        ),
    ]
