# Generated by Django 4.0.4 on 2022-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0004_alter_decreaseofincome_decrease_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='decreaseofincome',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='incomeofcourier',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='increaseofincome',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weeklysalary',
            name='date',
            field=models.DateField(),
        ),
    ]
