# Generated by Django 4.0.4 on 2022-05-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0005_alter_dailysalary_date_alter_decreaseofincome_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='status',
            field=models.CharField(choices=[('Calculated', 'Calculated'), ('Not calculated', 'Not calculated')], default='Not calculated', max_length=15),
        ),
    ]
