# Generated by Django 4.0.4 on 2022-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0006_alter_dailysalary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='status',
            field=models.CharField(choices=[('C', 'calculated for weekly salary'), ('N', 'not calculated for weekly salary')], default='not calculated for weekly salary', max_length=1),
        ),
    ]
