# Generated by Django 4.0.4 on 2022-05-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0007_alter_dailysalary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='status',
            field=models.CharField(choices=[('C', 'c'), ('N', 'n')], default='n', max_length=1),
        ),
    ]
