# Generated by Django 4.0.4 on 2022-05-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0008_alter_dailysalary_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysalary',
            old_name='status',
            new_name='status_for_weekly',
        ),
    ]
